### ISSUE TITLE
Добавить якорь для CSS-свойства

### ISSUE THREAD

**Issue by nikolai-shabalin** [nikolai-shabalin/css-properties#27]
Чтобы удобнее делиться ссылкой

**Comment by AnnaVita1** [comment]
Если бы чуть подробнее описание задания, что конкретно куда добавить (для тех, кто только в танке, то есть только 2 модуль прошёл)

**Comment by nikolai-shabalin** [comment]
Под "якорем" подразумевается ссылка к определённому месту на странице.

Первая часть.
Например, `<a href="#margin-trim">`. Обрати внимание на `#` в начале.
Такая ссылка будет скролить страницу к элементу с `<li id="margin-trim">`. Поэтому в twig-шаблоне к `<li class="properties__item">` нужно добавить `id="{{property.name}}"`, тогда у нас будут уникальные `id` к каждому CSS-свойству.

Вторая часть это создать ссылки.
Тут предложу вариант как с заголовком в гитхабе https://github.com/nikolai-shabalin/css-properties. При наведении на заголовок в Readme.md появляется ссылка с такой картинкой
![image](https://user-images.githubusercontent.com/2378233/227701197-b44b4b46-f88c-4718-988f-7abc90570757.png)

Путь ссылки формируется точно также как и `id` - `<a href="#{{property.name}}>"`. В этом случае мы уверены, что ссылка ведёт к правильному блоку

Третья часть.
При клике на якорную ссылку путь копирется в буфер обмена - https://habr.com/ru/company/ruvds/blog/358494/
