### ISSUE TITLE
Добавить группировку по...

### ISSUE THREAD

**Issue by elli0thammer** [nikolai-shabalin/css-properties#8]
Предложение: сгруппировать свойства по применению, например, флексовые свойства.
Или сгруппировать по группе, например, background.
А также добавить поиск по свойствам, чтобы найти нужное.

**Comment by nikolai-shabalin** [comment]
А зачем поиск по свойствам? Это же не справочник, что делает свойство. Вот например вы нашли `background-blend-mode` и узнали что он вышел `20.05.2014` и для чего эта информация вам может понадобиться? Опишите такую ситуацию, когда поиск понадобиться.

Сейчас цель, что-то вроде "А что там вышло в 2021?", а то я уже документацию 2 года не читал. Ну заодно и за 2022 год посмотрю.

**Comment by nikolai-shabalin** [comment]
Про группировку тоже думаю. Вот есть группировка по `background` и мы узнаём, что `background-blend-mode` вышел позже всех из всех `background-*`  свойств. Но зачем я пошёл это узнавать именно в таком виде?

**Comment by elli0thammer** [comment]
Понятна мысль. Визуально, когда заходишь на сайт, не хватает чего-то такого, чтобы выглядело более минималистично (по-моему субъективному мнению). В таком случае, группировать по годам имеет смысл? Видеть блоки: 2022 г, 2021 г и т.д.  Это бы и создало систематизацию. Заходишь в блок 2022 г и видишь все свойства, которые вышли в этот период. Идея не совпадает с первичным замыслом?

**Comment by nikolai-shabalin** [comment]
> В таком случае, группировать по годам имеет смысл? Видеть блоки: 2022 г, 2021 г и т.д. Это бы и создало систематизацию. Заходишь в блок 2022 г и видишь все свойства, которые вышли в этот период. Идея не совпадает с первичным замыслом?

Да, группировка по годам планировалась. 

> когда заходишь на сайт, не хватает чего-то такого, чтобы выглядело более минималистично (по-моему субъективному мнению).

Пока дизайна вообще нет, но это легко сделать: и минималистично, и красиво, и как угодно =)

**Comment by nikolai-shabalin** [comment]
Если есть желание и возможность, то группировку вы можете помочь сделать.

В [index.twig](https://github.com/nikolai-shabalin/css-properties/blob/main/site/index.twig) приходит объект `properties`, где у каждого свойства(`property`) есть набор полей:

```json
{
  "name": "rotate",
  "date": "2022-08-02",
  "mdnUrl": "https://developer.mozilla.org/docs/Web/CSS/rotate","specUrl":"https://drafts.csswg.org/css-transforms-2/#individual-transforms",
  "year": 2022
}
```
собственно по полю `year` можно группировать

**Comment by elli0thammer** [comment]
Интересная задача, но у меня пока недостаточно знаний для реализации чего-то такого. Хотелось поучаствовать в проекте хотя бы так.

**Comment by nikolai-shabalin** [comment]
Всегда можно попробовать. Ну смотрите сами...

Есть лёгкая задача добавить [editorConfig](https://github.com/nikolai-shabalin/css-properties/issues/1). Ну и отталкиваясь от ваших знаний вы можете как-то улучшить проект. Необязательно то, что есть в ишью.

**Comment by nikolai-shabalin** [comment]
Добавил группировку по году
